# Generated by Django 6.1.1 on 2026-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=100)),
                ('identificador_fuente', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('url_original', models.URLField(max_length=1000)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fuente', 'identificador_fuente'), name='propiedad_unicar_por_fuente')],
            },
        ),
    ]
