# Generated by Django 6.1.1 on 2026-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
