# Generated by Django 6.1.1 on 2026-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='en_alquiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='en_venta',
            field=models.BooleanField(default=False),
        ),
    ]
