# Generated by Django 6.1.1 on 2026-09-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_en_alquiler_propiedad_en_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='moneda_alquiler',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='moneda_venta',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_alquiler',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
