# Generated by Django 6.1.1 on 2026-09-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_propiedad_moneda_alquiler_propiedad_moneda_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='precio',
        ),
    ]
