# Generated by Django 6.1.1 on 2026-09-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_remove_propiedad_moneda_remove_propiedad_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='dormitorios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='dormitorios_verificados',
            field=models.BooleanField(default=False),
        ),
    ]
