# Generated by Django 6.1.1 on 2026-10-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_propiedad_dormitorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
