# Generated by Django 6.1.1 on 2026-10-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_propiedad_latitud_propiedad_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ambientes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='banos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='caracteristicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='provincia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='zona',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
