# Generated by Django 6.1.1 on 2026-10-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_propiedad_ambientes_propiedad_banos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='radio_ubicacion_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ubicacion_aproximada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
