# Generated by Django 6.1.1 on 2026-10-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0009_propiedad_radio_ubicacion_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='ciudad_origen',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='provincia_origen',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ConsultaLocalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('ciudad', models.CharField(blank=True, max_length=150)),
                ('provincia', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(max_length=20)),
                ('consultada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('latitud', 'longitud'), name='consulta_localidad_por_coordenadas')],
            },
        ),
    ]
